# Game Configuration
game:
  name: "BeTheMC"
  version: "0.1.0"
  story_mode: true
  save_slots: 3
  auto_save_interval: 5  # minutes
  anime_style: true  # Focus on anime-style storytelling

# Save Configuration
save_dir: "data/saves"

# Story Configuration
story:
  # Story progression settings
  max_history_length: 20  # How many past choices to remember
  branching_depth: 3     # How many steps ahead to generate story branches
  
  # Choice impact weights - anime-style focus
  choice_weights:
    personality: 0.5     # How much player's personality affects story
    relationships: 0.3   # How much NPC relationships affect story
    location: 0.15      # How much current location affects story
    past_choices: 0.05  # How much past choices affect story

  # Anime-style scene types (no rigid battle mechanics)
  scene_types:
    dialogue:
      min_options: 2
      max_options: 4
      time_limit: 0  # No time pressure
    exploration:
      min_options: 3
      max_options: 5
      time_limit: 0
    encounter:
      min_options: 2
      max_options: 4
      time_limit: 0  # No rigid battle system
    friendship:
      min_options: 2
      max_options: 3
      time_limit: 0
    adventure:
      min_options: 2
      max_options: 4
      time_limit: 0

# AI Configuration
ai:
  # LLM Configuration
  llm:
    provider: "local"
    model: "gemma3:27b"
    temperature: 0.8
    max_tokens: 1500
    api_base: "http://192.168.1.68:11434/api/generate"
    api_key: ""
    
  # Embedder Configuration
  embedder:
    provider: "sentence-transformers"
    model: "all-MiniLM-L6-v2"
    api_base: ""
    api_key: ""
    
  # Story generation settings - anime-style focus
  story_generation:
    context_window: 10  # How many past scenes to consider
    creativity_factor: 0.9  # Higher creativity for anime-style stories
    consistency_weight: 0.6  # Less rigid consistency, more fluid storytelling
    
  # Character generation - anime-style
  character_generation:
    personality_depth: 0.9  # Deep character development
    relationship_complexity: 0.8  # Complex relationships like anime
    dialogue_style: 0.8  # Natural, flowing dialogue
    friendship_focus: 0.9  # Emphasize friendship and bonds

# Vector Database Configuration
vector_store:
  provider: "qdrant"
  host: "localhost"
  port: 6333
  collections:
    story_segments:
      name: "story_segments"
      vector_size: 384  # Sentence transformers size
      similarity_threshold: 0.85
    character_memories:
      name: "character_memories"
      vector_size: 384
      similarity_threshold: 0.8
    player_choices:
      name: "player_choices"
      vector_size: 384
      similarity_threshold: 0.75
  max_results: 5

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/game.log"
  rotation:
    max_size: "10MB"
    backup_count: 5 